CREATE TABLE CACHE_USER_FLAG
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    FLAG_NAME VARCHAR(255) NOT NULL,
    FLAG_DESCIPTION CLOB(1M),
    PRIMARY KEY(SYS_UUID),
    UNIQUE(FLAG_NAME)
);

INSERT INTO DB_VERSION(VERSION_NO, INSTALLED) VALUES (3, CURRENT_TIMESTAMP);