CREATE TABLE GC_CONFIGURATION
(
    CONF_KEY VARCHAR(1023) NOT NULL,
    CONF_VALUE BLOB NOT NULL,
    CONF_VERSION BIGINT NOT NULL DEFAULT 1,
    PRIMARY KEY(CONF_KEY)
);

INSERT INTO DB_VERSION(VERSION_NO, INSTALLED) VALUES (2, CURRENT_TIMESTAMP);