CREATE TABLE DB_VERSION
(
    VERSION_NO BIGINT NOT NULL,
    INSTALLED TIMESTAMP NOT NULL,
    PRIMARY KEY(VERSION_NO)
);

CREATE TABLE GC_CONFIGURATION
(
    CONF_KEY VARCHAR(1023) NOT NULL,
    CONF_VALUE BLOB NOT NULL,
    CONF_VERSION BIGINT NOT NULL DEFAULT 1,
    PRIMARY KEY(CONF_KEY)
);

CREATE TABLE CACHE_USER_FLAG
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    FLAG_NAME VARCHAR(255) NOT NULL,
    FLAG_DESCIPTION CLOB(1M),
    PRIMARY KEY(SYS_UUID),
    UNIQUE(FLAG_NAME)
);

CREATE TABLE GPX_IMPORT
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    IMPORTED TIMESTAMP NOT NULL,
    FILENAME VARCHAR(1023),
    GPX_NAME VARCHAR(1023),
    GPX_TIMESTAMP TIMESTAMP,
    GPX_BOUNDS_MINLAT DOUBLE PRECISION,
    GPX_BOUNDS_MAXLAT DOUBLE PRECISION,
    GPX_BOUNDS_MINLON DOUBLE PRECISION,
    GPX_BOUNDS_MAXLON DOUBLE PRECISION,
    IMPORTED_ITEMS BIGINT NOT NULL DEFAULT 0,
    IMPORT_LOG CLOB(5M),
    PRIMARY KEY(SYS_UUID)
);

CREATE TABLE GEOCACHE
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    GC_CODE VARCHAR(255) NOT NULL,
    PRIMARY KEY(SYS_UUID),
    UNIQUE(GC_CODE)
);

CREATE TABLE GCUSER
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    GC_USER_ID BIGINT NOT NULL,
    GC_USERNAME VARCHAR(1023) NOT NULL,
    PRIMARY KEY(SYS_UUID),
    UNIQUE(GC_USER_ID)
);

CREATE TABLE CACHESYMBOL
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    SYMBOL_NAME VARCHAR(255) NOT NULL,
    IMG_DATA BLOB(255K),
    PRIMARY KEY(SYS_UUID),
    UNIQUE(SYMBOL_NAME)
);

CREATE TABLE CACHEATTRIBUTE
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    ATTRIBUTE_ID INT NOT NULL,
    ATTRIBUTE_TEXT VARCHAR(1023) NOT NULL,
    MODE SMALLINT NOT NULL,
    IMG_DATA BLOB(255K),
    PRIMARY KEY(SYS_UUID),
    UNIQUE(ATTRIBUTE_ID, MODE)
);

CREATE TABLE CONTAINER
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    CONTAINER_NAME VARCHAR(255) NOT NULL,
    IMG_DATA BLOB(255K),
    PRIMARY KEY(SYS_UUID),
    UNIQUE(CONTAINER_NAME)
);

CREATE TABLE CACHETYPE
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    TYPE_NAME VARCHAR(255) NOT NULL,
    IMG_DATA BLOB(255K),
    PRIMARY KEY(SYS_UUID),
    UNIQUE(TYPE_NAME)
);

CREATE TABLE COUNTRY
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    COUNTRY_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(SYS_UUID),
    UNIQUE(COUNTRY_NAME)
);

CREATE TABLE CSTATE
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    STATE_NAME VARCHAR(255) NOT NULL,
    COUNTRY CHAR(16) FOR BIT DATA NOT NULL REFERENCES COUNTRY (SYS_UUID) ON DELETE CASCADE,
    PRIMARY KEY(SYS_UUID),
    UNIQUE(STATE_NAME)
);

CREATE TABLE CACHEDATA
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    GEOCACHE CHAR(16) FOR BIT DATA NOT NULL REFERENCES GEOCACHE (SYS_UUID) ON DELETE CASCADE,
    GPX_SOURCE CHAR(16) FOR BIT DATA DEFAULT NULL REFERENCES GPX_IMPORT (SYS_UUID) ON DELETE SET NULL,
    LONGITUDE DOUBLE PRECISION,
    LATITUDE DOUBLE PRECISION,
    CORRECTED_LONGITUDE DOUBLE PRECISION,
    CORRECTED_LATITUDE DOUBLE PRECISION,
    PLACED_BY VARCHAR(1023),
    OWNER CHAR(16) FOR BIT DATA NOT NULL REFERENCES GCUSER (SYS_UUID) ON DELETE RESTRICT,
    GC_URL VARCHAR(1023),
    CACHESYMBOL CHAR(16) FOR BIT DATA NOT NULL REFERENCES CACHESYMBOL (SYS_UUID) ON DELETE RESTRICT,
    CACHENAME VARCHAR(2047) NOT NULL,
    DIFFICULTY DECIMAL(1,1),
    TERRAIN DECIMAL(1,1),
    GC_ID BIGINT,
    PLACED TIMESTAMP,
    AVAILABLE SMALLINT,
    ARCHIVED SMALLINT,
    CONTAINER CHAR(16) FOR BIT DATA NOT NULL REFERENCES CONTAINER (SYS_UUID) ON DELETE RESTRICT,
    CACHETYPE CHAR(16) FOR BIT DATA NOT NULL REFERENCES CACHETYPE (SYS_UUID) ON DELETE RESTRICT,
    CSTATE CHAR(16) FOR BIT DATA DEFAULT NULL REFERENCES CSTATE (SYS_UUID) ON DELETE SET NULL,
    LONG_DESCRIPTION CLOB(5M),
    LONG_DESC_HTML SMALLINT,
    SHORT_DESCRIPTION CLOB(1M),
    SHORT_DESC_HTML SMALLINT,
    HINT CLOB(128K),
    PRIMARY KEY(SYS_UUID)
);

CREATE TABLE CACHEATTRIBUTES
(
    CACHE CHAR(16) FOR BIT DATA NOT NULL REFERENCES CACHEDATA (SYS_UUID) ON DELETE CASCADE,
    ATTRIBUTE CHAR(16) FOR BIT DATA NOT NULL REFERENCES CACHEATTRIBUTE (SYS_UUID) ON DELETE CASCADE,
    PRIMARY KEY (CACHE, ATTRIBUTE)
);

CREATE TABLE LOGTYPE
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    LOGTYPE_NAME VARCHAR(255) NOT NULL,
    IMG_DATA BLOB(255K),
    PRIMARY KEY(SYS_UUID),
    UNIQUE(LOGTYPE_NAME)
);

CREATE TABLE CACHELOGS
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    CACHE CHAR(16) FOR BIT DATA NOT NULL REFERENCES CACHEDATA (SYS_UUID) ON DELETE CASCADE,
    AUTHOR CHAR(16) FOR BIT DATA NOT NULL REFERENCES GCUSER (SYS_UUID) ON DELETE RESTRICT,
    LOGTYPE CHAR(16) FOR BIT DATA NOT NULL REFERENCES LOGTYPE (SYS_UUID) ON DELETE RESTRICT,
    GC_ID BIGINT NOT NULL,
    LOGTEXT CLOB(512K),
    ENCODED SMALLINT,
    LOGGED TIMESTAMP,
    PRIMARY KEY(SYS_UUID)
);

CREATE TABLE TRAVELBUG
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    REF_CODE VARCHAR(255) NOT NULL,
    TB_NAME VARCHAR(1023),
    SECRET_CODE VARCHAR(255),
    OWNING SMALLINT,
    PRIMARY KEY(SYS_UUID),
    UNIQUE(REF_CODE)
);

CREATE TABLE CACHETB
(
    CACHE CHAR(16) FOR BIT DATA REFERENCES CACHEDATA (SYS_UUID) ON DELETE CASCADE,
    TRAVELBUG CHAR(16) FOR BIT DATA REFERENCES TRAVELBUG (SYS_UUID) ON DELETE RESTRICT,
    PRIMARY KEY (CACHE, TRAVELBUG)
);

INSERT INTO DB_VERSION(VERSION_NO, INSTALLED) VALUES (1, CURRENT_TIMESTAMP);