CREATE TABLE DB_VERSION
(
    VERSION_NO BIGINT NOT NULL,
    INSTALLED TIMESTAMP NOT NULL,
    PRIMARY KEY(VERSION_NO)
);

INSERT INTO DB_VERSION(VERSION_NO, INSTALLED) VALUES (1, CURRENT_TIMESTAMP);