CREATE TABLE DB_VERSION
(
    VERSION_NO BIGINT NOT NULL,
    INSTALLED TIMESTAMP NOT NULL,
    PRIMARY KEY(VERSION_NO)
);

CREATE TABLE GC_CONFIGURATION
(
    CONF_KEY VARCHAR(1023) NOT NULL,
    CONF_VALUE BLOB NOT NULL,
    CONF_VERSION BIGINT NOT NULL DEFAULT 1,
    PRIMARY KEY(CONF_KEY)
);

CREATE TABLE CACHE_USER_FLAG
(
    SYS_UUID CHAR(16) FOR BIT DATA,
    FLAG_NAME VARCHAR(255) NOT NULL,
    FLAG_DESCIPTION CLOB(1M),
    PRIMARY KEY(SYS_UUID),
    UNIQUE(FLAG_NAME)
);

INSERT INTO DB_VERSION(VERSION_NO, INSTALLED) VALUES (1, CURRENT_TIMESTAMP);